name: TheBackrooms
version: 1.0.0
main: io.bluewiz.backrooms.BackroomsPlugin
api-version: "1.21.11"
description: "No-clip out of reality. No escape."
authors: [bluewiz_360]

commands:
  backrooms:
    description: "Send a player to the Backrooms. Good luck."
    usage: "/<command> [player|reload|leave|list]"
    permission: backrooms.enter
    permission-message: "You are already in the Backrooms."

permissions:
  backrooms.enter:
    description: "Can use /backrooms"
    default: op
  backrooms.send:
    description: "Can send other players to the Backrooms"
    default: op
  backrooms.admin:
    description: "Can use /backrooms reload, leave, and list"
    default: op
